/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vue;

import DAO.compteDAO;
import model.Pompier;

/**
 *
 * @author ilias.blaquiere
 */
public class Frm_Acceuil extends javax.swing.JFrame {

    /**
     * Creates new form connexion
     */
    public Frm_Acceuil() {
        initComponents();
    }

    public Frm_Acceuil(Pompier unPompier) {
        initComponents();
        jLabelProfilPompier.setText("Profil de " + unPompier.getNom_pompier());
        jLabelNomPompier.setText("Nom : " + unPompier.getNom_pompier());
        jLabelPrenomPompier.setText("Prenom : " + unPompier.getPrenom_pompier());
        jLabelDateNaissance.setText("Date de naissance : " + unPompier.getDateNaissance_pompier());
        jLabelNumeroBipPompier.setText("numero Bip : " + unPompier.getNumeroBip_pompier());
        jLabelTelPompier.setText("Tel : " + unPompier.getTel_pompier());
        jLabelSexePompier.setText("Sexe : " + unPompier.getSexe_pompier());
        jLabelRolePompier.setText("Role : " + unPompier.getRole_pompier());
        jLabelCasernePompier.setText("Caserne : " + unPompier.getUneCaserne().getNom_caserne());
        
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelProfilPompier = new javax.swing.JLabel();
        jLabelNomPompier = new javax.swing.JLabel();
        jLabelPrenomPompier = new javax.swing.JLabel();
        jLabelDateNaissance = new javax.swing.JLabel();
        jLabelNumeroBipPompier = new javax.swing.JLabel();
        jLabelTelPompier = new javax.swing.JLabel();
        jLabelSexePompier = new javax.swing.JLabel();
        jLabelRolePompier = new javax.swing.JLabel();
        jLabelCasernePompier = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabelProfilPompier.setText("Profil de : *nom du pompier*");

        jLabelNomPompier.setText("jLabelNomPompier");

        jLabelPrenomPompier.setText("jLabelPrenomPompier");

        jLabelDateNaissance.setText("jLabelDateNaissance");

        jLabelNumeroBipPompier.setText("jLabelNumeroBipPompier");

        jLabelTelPompier.setText("jLabelTelPompier");

        jLabelSexePompier.setText("jLabelSexePompier");

        jLabelRolePompier.setText("jLabelRolePompier");

        jLabelCasernePompier.setText("jLabelCasernePompier");

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setText("Accueil");
        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setText("Liste des internes");
        jMenuBar1.add(jMenu2);

        jMenu4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu4.setText("Liste des véhicules");
        jMenu4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenu4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomPompier)
                            .addComponent(jLabelPrenomPompier)
                            .addComponent(jLabelDateNaissance)
                            .addComponent(jLabelNumeroBipPompier))
                        .addGap(172, 172, 172)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCasernePompier)
                            .addComponent(jLabelSexePompier)
                            .addComponent(jLabelTelPompier)
                            .addComponent(jLabelRolePompier)))
                    .addComponent(jLabelProfilPompier))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelProfilPompier)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomPompier)
                    .addComponent(jLabelTelPompier))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrenomPompier)
                    .addComponent(jLabelSexePompier))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDateNaissance)
                    .addComponent(jLabelRolePompier))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumeroBipPompier)
                    .addComponent(jLabelCasernePompier))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Acceuil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCasernePompier;
    private javax.swing.JLabel jLabelDateNaissance;
    private javax.swing.JLabel jLabelNomPompier;
    private javax.swing.JLabel jLabelNumeroBipPompier;
    private javax.swing.JLabel jLabelPrenomPompier;
    private javax.swing.JLabel jLabelProfilPompier;
    private javax.swing.JLabel jLabelRolePompier;
    private javax.swing.JLabel jLabelSexePompier;
    private javax.swing.JLabel jLabelTelPompier;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
